In [3]:
import pandas as pd

df = pd.read_csv('../data/European_Bank.csv')
df.head()

,Year,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,2025,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2025,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,2025,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,2025,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,2025,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0


In [4]:
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Year             10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


Year               0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.drop(['CustomerId','Surname'], axis=1, inplace=True)

In [9]:
df["Geography"].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [10]:
df["Gender"].unique()

array(['Female', 'Male'], dtype=object)

In [11]:
df["Exited"].unique()

array([1, 0])

In [12]:
df["HasCrCard"].unique()
df["IsActiveMember"].unique()

array([1, 0])

In [14]:
df["Age"].min()

np.int64(18)

In [15]:

df["Age"].max()

np.int64(92)

In [16]:
df["Balance"].min()


np.float64(0.0)

In [17]:
df["Balance"].max()

np.float64(250898.09)

In [18]:
df["CreditScore"].min()

np.int64(350)

In [19]:
df["CreditScore"].max()

np.int64(850)

In [20]:
df["Exited"].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [21]:
df["Exited"].value_counts(normalize=True)*100

Exited
0    79.63
1    20.37
Name: proportion, dtype: float64

In [22]:
(df["Balance"] == 0).sum()

np.int64(3617)

In [23]:
(df["Balance"] == 0).mean() * 100

np.float64(36.17)

In [24]:
df["Year"].unique()

array([2025])

In [26]:
df.drop(
    columns=["Year"],
    inplace=True
)